# Generated by Django 4.2.3 on 2023-07-14 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_user_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 14, 1, 25, 31, 353811, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
