# Generated by Django 4.2.3 on 2023-07-20 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_user_date_joined_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 20, 13, 9, 54, 514811, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
