# Generated by Django 4.2.3 on 2023-07-11 19:03

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=2, editable=False, populate_from="title", unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="questions",
                to="quiz.quiz",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="title",
            field=models.CharField(
                default="New Quiz",
                max_length=255,
                unique=True,
                verbose_name="Quiz Title",
            ),
        ),
    ]
