# Generated by Django 4.2.3 on 2023-07-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_quiz_slug_alter_question_quiz_alter_quiz_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="slug",
        ),
    ]
