# Generated by Django 4.2.3 on 2023-07-11 19:11

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_remove_quiz_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=3, editable=False, populate_from="title", unique=True
            ),
            preserve_default=False,
        ),
    ]
