# Generated by Django 4.2.3 on 2023-07-12 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_quiz_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="is_active",
        ),
    ]
