# Generated by Django 4.2.3 on 2023-07-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_alter_answer_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="is_right",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
