# Generated by Django 4.2.3 on 2023-07-20 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0009_alter_question_quiz_alter_quiz_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
